name: Compile and publish CV
on:
  push:
    branches:
      main

jobs:
  update_cv:
    runs-on: ubuntu-latest
    name: A job to make CV
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make CV pdf
        uses: ./
        id: publish
      - run: ls
      - run: cd CV
      - run: ls
      - run: git add CV/main.tex
      - run: git commit -m "Publish CV.tex"
      - run: git push origin HEAD:gh-pages --force
